# Generated by Django 2.2.2 on 2020-04-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=25, upload_to='pics'),
            preserve_default=False,
        ),
    ]
